services:
  mysql-db:
    image: mysql:8.0
    container_name: petclinic-mysql
    restart: always  # Good practice for EC2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql-data:/var/lib/mysql

  petclinic-app:
    build: .
    container_name: petclinic-web
    restart: always  # Restart app if it crashes
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      # Note: 'mysql-db' matches the service name above for internal networking
      - MYSQL_URL=jdbc:mysql://mysql-db:3306/petclinic
      - MYSQL_USER=root
      - MYSQL_PASS=petclinic
    depends_on:
      - mysql-db

volumes:
  mysql-data: