name: PetClinic CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: Security and Quality Analysis
  test:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
          # fetch-depth: 0 is required for Sonar to see git history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw verify sonar:sonar \
          -pmysql \
          -Dsonar.projectKey=RojanShrestha1_DevOps-PetClinic \
          -Dsonar.organization=rojanshrestha1 \
          -Dsonar.host.url=https://sonarcloud.io/

  # JOB 2: Packaging and Shipping
  build:
    name: Build and Push Docker Image
    needs: test  # This job ONLY runs if the Sonar scan passes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR with Maven
        run: ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic:latest

  # # JOB 3: Test Deployment (The "Manual" Pull)
  # deploy:
  #   name: Deploy to EC2
  #   needs: build # Only runs after the image is safe in Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Execute Remote SSH Commands
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.EC2_HOST }}       # Your EC2 Public IP
  #         username: ec2-user
  #         key: ${{ secrets.EC2_SSH_KEY }}      # Your .pem file content
  #         script: |
  #           # Pull the latest image
  #           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic:latest
  #           # Stop existing container if it's running
  #           docker stop petclinic || true
  #           docker rm petclinic || true
  #           # Run the fresh version
  #           docker run -d -p 80:8080 --name petclinic ${{ secrets.DOCKERHUB_USERNAME }}/spring-petclinic:latest